CREATE DATABASE Biblioteca;
-- DROP DATABASE Biblioteca;
USE Biblioteca;

CREATE TABLE PERSONA (
    CI INTEGER PRIMARY KEY NOT NULL,
    Nombre VARCHAR(50) NOT NULL,
    Telefono INTEGER NOT NULL,
    Direccion VARCHAR(100)NOT NULL,
    Correo VARCHAR(50) NOT NULL
);

CREATE TABLE MATERIALBIBLIOGRAFICO (
    Codigo INTEGER PRIMARY KEY NOT NULL,
    Titulo VARCHAR(60),
    NroPag SMALLINT NOT NULL,
    Tipo CHAR NOT NULL
);

CREATE TABLE LIBRO (
    Codigo INTEGER NOT NULL PRIMARY KEY,
    Editorial VARCHAR(60) NOT NULL,
    AñoPub INTEGER NOT NULL,
    ISBN INTEGER NOT NULL,
    Edicion VARCHAR(50) NOT NULL, 
    FOREIGN KEY (Codigo) REFERENCES MATERIALBIBLIOGRAFICO(Codigo)
		ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE TESIS (
    Codigo INTEGER NOT NULL PRIMARY KEY,
    FechaDefensa DATE NOT NULL,
    Tutor VARCHAR(50) NOT NULL,
    FOREIGN KEY (Codigo) REFERENCES MATERIALBIBLIOGRAFICO(Codigo)
		ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE REVISTA (
    Codigo INTEGER NOT NULL PRIMARY KEY,
    Nro INTEGER NOT NULL, 
    Año INTEGER NOT NULL, 
    FOREIGN KEY (Codigo) REFERENCES MATERIALBIBLIOGRAFICO(Codigo)
		ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE FICHAPRESTAMO (
    Nro INTEGER PRIMARY KEY NOT NULL,
    Fecha DATE NOT NULL,
    Hora TIME NOT NULL,
    FechaDev DATE NOT NULL,
    CIPersona INTEGER NOT NULL,
    CodigoMB INTEGER NOT NULL,
    FOREIGN KEY (CIPersona) REFERENCES PERSONA(CI)
		ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (CodigoMB) REFERENCES MATERIALBIBLIOGRAFICO(Codigo)
		ON UPDATE CASCADE
        ON DELETE CASCADE
);
