CREATE DATABASE ARBOLG2024SC;
USE ARBOLG2024SC;

CREATE TABLE PERSONA(
	ID INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR (60) NOT NULL, 
    SEXO CHAR NOT NULL, 
    IDPADRE INTEGER, 
    IDMADRE INTEGER, 
    FOREIGN KEY (IDPADRE) REFERENCES PERSONA(ID)
		ON UPDATE NO ACTION 
        ON DELETE NO ACTION,
	FOREIGN KEY (IDMADRE) REFERENCES PERSONA(ID)
		ON UPDATE NO ACTION 
        ON DELETE NO ACTION
);

INSERT INTO PERSONA VALUES (1, 'Joaquin Chumacero', 'M', NULL, NULL);
INSERT INTO PERSONA VALUES (2, 'Carmen Colque', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES (3, 'Pedro Chumacero Choque', 'M', 1, 2);
INSERT INTO PERSONA VALUES (4, 'Patricia Aguilera', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES (5, 'Joaquin Chumacero Aguilera', 'M', 3, 4);
INSERT INTO PERSONA VALUES (6, 'Fabiola Mendez', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES (7, 'Joaquin Jr. Chumacero Mendez', 'M', 5, 6);
INSERT INTO PERSONA VALUES (8, 'Carla Chumacero Mendez', 'F', 5, 6);
INSERT INTO PERSONA VALUES (9, 'Carla Camacho', 'F', NULL, NULL);
INSERT INTO PERSONA VALUES (10, 'Carlos Chumacero Camacho', 'M', 5, 9);
SELECT * FROM PERSONA;

/* Mostrar el nombre del padre de Joaquin Chumacero Aguilera */
SELECT PADRE.ID, PADRE.NOMBRE
FROM PERSONA PADRE, PERSONA HIJO
WHERE HIJO.IDPADRE=PADRE.ID AND HIJO.NOMBRE='Joaquin Chumacero Aguilera';

SELECT PADRE.ID, PADRE.NOMBRE
FROM PERSONA PADRE
WHERE PADRE.ID = (
    SELECT HIJO.IDPADRE
    FROM PERSONA HIJO
    WHERE HIJO.NOMBRE = 'Joaquin Chumacero Aguilera'
);

/* Mostrar los nombres de los hijos de Joaquin Chumacero Aguilera */
SELECT HIJO.ID, HIJO.NOMBRE
FROM PERSONA PADRE, PERSONA HIJO
WHERE PADRE.ID=HIJO.IDPADRE AND PADRE.NOMBRE='Joaquin Chumacero Aguilera';

SELECT ID, NOMBRE
FROM PERSONA
WHERE IDPADRE IN (SELECT ID
      FROM PERSONA
      WHERE NOMBRE = 'JOAQUIN CHUMACERO AGUILERA'
);

/* Mostrar el nombre del abuelo paterno de Joaquin Chumacero Aguilera */
SELECT ABUELO.ID, ABUELO.NOMBRE
FROM PERSONA ABUELO
WHERE ABUELO.ID = (
    SELECT PADRE.IDPADRE
    FROM PERSONA PADRE
    WHERE PADRE.ID = (
        SELECT HIJO.IDPADRE
        FROM PERSONA HIJO
        WHERE HIJO.NOMBRE = 'Joaquin Chumacero Aguilera'
    )
);
