CREATE DATABASE PROYECTOGRADO2024;
USE PROYECTOGRADO2024;
DROP DATABASE PROYECTOGRADO2024;

CREATE TABLE GRUPOINV (
	NRO INTEGER NOT NULL PRIMARY KEY, 
    NOMBRE VARCHAR(60) NOT NULL,
    NROCOMPONENTES INTEGER NOT NULL
);

CREATE TABLE ALUMNO (
	REGISTRO INTEGER NOT NULL PRIMARY KEY, 
    CI INTEGER NOT NULL, 
    NOMBRE VARCHAR(60) NOT NULL,
    NROGRUPO INTEGER NOT NULL,
    FOREIGN KEY (NROGRUPO) REFERENCES GRUPOINV(NRO) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE
);

CREATE TABLE DOCENTE (
	CI INTEGER NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(60) NOT NULL, 
    DOMICILIO VARCHAR(60) NOT NULL
);

CREATE TABLE PROYECTOGRADO (
	NROORDEN INTEGER NOT NULL PRIMARY KEY,
    TEMA VARCHAR (100) NOT NULL,
    FECHACOMIENZO DATE NOT NULL,
    REGISTROA INTEGER NOT NULL,
    CIDOCENTE INTEGER NOT NULL,
    FOREIGN KEY (REGISTROA) REFERENCES ALUMNO(REGISTRO) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE,
    FOREIGN KEY (CIDOCENTE) REFERENCES DOCENTE(CI) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE
);

CREATE TABLE COLABORA(
	NROORDEN INTEGER NOT NULL,
	CIDOCENTE INTEGER NOT NULL, 
	PRIMARY KEY (CIDOCENTE, NROORDEN),
	FOREIGN KEY (CIDOCENTE) REFERENCES DOCENTE(CI) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE,
    FOREIGN KEY (NROORDEN) REFERENCES PROYECTOGRADO(NROORDEN) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE
);

CREATE TABLE TRIBUNAL (
	NRO INTEGER NOT NULL PRIMARY KEY, 
    LUGAR VARCHAR(60) NOT NULL, 
    FECHADEFENSA DATE NOT NULL, 
    NROORDEN INTEGER NOT NULL,
    FOREIGN KEY (NROORDEN) REFERENCES PROYECTOGRADO(NROORDEN) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE
);
CREATE TABLE FORMA (
	NROTRIB INTEGER NOT NULL,
	CIDOCENTE INTEGER NOT NULL, 
	PRIMARY KEY (CIDOCENTE, NROTRIB),
	FOREIGN KEY (CIDOCENTE) REFERENCES DOCENTE(CI) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE,
    FOREIGN KEY (NROTRIB) REFERENCES TRIBUNAL(NRO) 
    ON UPDATE CASCADE 
    ON DELETE CASCADE
);

INSERT INTO GRUPOINV VALUES (100, 'Programadores eternos', 2);
INSERT INTO GRUPOINV VALUES (101, 'Los IA', 3);

INSERT INTO ALUMNO VALUES (111, 325, 'Joaquin Chumcero', 100);
INSERT INTO ALUMNO VALUES (222, 445, 'Saturnino Mamani', 101);
INSERT INTO ALUMNO VALUES (333, 654, 'Fabiola Mendez', 100);
INSERT INTO ALUMNO VALUES (444, 789, 'Carlos Camacho', 101);
INSERT INTO ALUMNO VALUES (555, 898, 'Patricia Aguilera', 101);

INSERT INTO PROYECTOGRADO VALUES (1001, 'Software academico colegio San Sebastian', '2020-01-10', 777, 111);
INSERT INTO PROYECTOGRADO VALUES (1002, 'Sistema de informacion contable empresa Los laureles', '2021-03-15', 999, 333);

INSERT INTO DOCENTE VALUES (777, 'Natalia Coronado', 'Urb. Los penocos');
INSERT INTO DOCENTE VALUES (888, 'Pedro Claure', 'Calle landivar');
INSERT INTO DOCENTE VALUES (999, 'Antonio Perez', 'Calle Seoane');
INSERT INTO DOCENTE VALUES (101, 'Martha Quispe', 'Calle landivar');
INSERT INTO DOCENTE VALUES (112, 'Felipe Cardenas', 'Urb. Los lirios');
INSERT INTO DOCENTE VALUES (113, 'Lidia Melendres', 'Urb. Los penocos');

INSERT INTO COLABORA VALUES (888, 1001);
INSERT INTO COLABORA VALUES (101, 1001);
INSERT INTO COLABORA VALUES (999, 1002);

INSERT INTO TRIBUNAL VALUES (1, 'Biblioteca', '2022-02-15', 1001);
INSERT INTO TRIBUNAL VALUES (2, 'Sala de Reuniones', '2022-12-20', 1002);

INSERT INTO FORMA VALUES (101, 1);
INSERT INTO FORMA VALUES (112, 1);
INSERT INTO FORMA VALUES (113, 1);
INSERT INTO FORMA VALUES (777, 2);
INSERT INTO FORMA VALUES (888, 2);
INSERT INTO FORMA VALUES (113, 2);

/* Mostrar el docente que ha dirigido el proyecto de grado  SOFTWARE ACADEMICO SAN SEBASTIAN*/
SELECT DOCENTE.CI, DOCENTE.NOMBRE
FROM DOCENTE, PROYECTOGRADO
WHERE CIDOCENTE=DOCENTE.CI AND PROYECTOGRADO.TEMA = 'SOFTWARE ACADEMICO SAN SEBASTIAN';

/* Mostrar los docentes que fueron tribunales en la defensa del Proyecto de grado SISTEMA DE INFORMACION CONTABLE EMPRESA LOS LAURELES */
SELECT DOCENTE.CI, DOCENTE.NOMBRE
FROM DOCENTE, FORMA, TRIBUNAL, PROYECTOGRADO
WHERE FORMA.CIDOCENTE = DOCENTE.CI AND TRIBUNAL.NRO=NROTRIB 
AND TRIBUNAL.NROORDEN=PROYECTOGRADO.NROORDEN AND PROYECTOGRADO.TEMA='SISTEMA DE INFORMACION CONTABLE EMPRESA LOS LAURELES';

/* Mostrar en cuantos tribunales ha participado el docente Lidia Melendres */
SELECT COUNT(*)
FROM DOCENTE, FORMA
WHERE DOCENTE.CI=FORMA.CIDOCENTE AND DOCENTE.NOMBRE='Lidia Melendres';
